name: Rust-wasm

on:
  push:
    branches: [ master ]
    paths:
    - 'wasm/rust-wasm/wasm-game-of-life/**'
    - '!wasm/rust-wasm/wasm-game-of-life/www/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'wasm/rust-wasm/wasm-game-of-life/**'
    - '!wasm/rust-wasm/wasm-game-of-life/www/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build
      run: cd wasm/rust-wasm/wasm-game-of-life/ && cargo build --verbose
#     - name: Run tests
#       run: cd wasm/rust-wasm/wasm-game-of-life/ && cargo test --verbose
