name: Rust

on:
  push:
    branches: [ master ]
    paths:
    - 'wasm/rust-wasm/wasm-game-of-life/**'
    - '!wasm/rust-wasm/wasm-game-of-life/www/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'wasm/rust-wasm/wasm-game-of-life/**'
    - '!wasm/rust-wasm/wasm-game-of-life/www/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
